version: "3"

services:
  dbt:
    image: mydbt:v1.0
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   target: dbt-postgres
    volumes:
      - .:/dbt
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    networks:
      - dbtnet
    command: [ "dbt run" ]

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${DBPORT}:${DBPORT}
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./pglogs:/var/log/postgresql
    networks:
      - dbtnet
    command:
      [
        "postgres",
        "-c",
        "log_statement=all",
        "-c",
        "log_destination=stderr"
      ]

networks:
  dbtnet:
    driver: bridge

volumes:
  pgdata:
  pglogs:
