version: "3"

services:
  dbt:
    build:
      context: .
      dockerfile: Dockerfile
      target: dbt-postgres
    container_name: dbt-con
    volumes:
      - ./.dbt:/root/.dbt
      - ./dbt_project.yml:/usr/app/dbt/dbt_project.yml
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    networks:
      - dbtnet
    command: "build"

  postgres:
    image: postgres:15
    container_name: mydbt-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${DB_PORT}:${DB_PORT}
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./pglogs:/var/log/postgresql
    networks:
      - dbtnet
    command:
      - "postgres"
      - "-c"
      - "log_statement=all"
      - "-c"
      - "log_destination=stderr"

networks:
  dbtnet:
    driver: bridge

volumes:
  pgdata:
  pglogs:
